services:
  weixin-mp:
    image: henryhe613/weixin-mp:0.4
    container_name: weixin-mp
    network_mode: host
    restart: unless-stopped
    environment:
      - APPID=
      - APPSECRET=
      - TEMPLATE_ID=
      - VERIFY_TOKEN=
      - MAIN_PATH=/wechat
      - DOMAIN=
      - WEB_PORT=8080
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=
      - REDIS_DB=0
      - MONGO_HOST=127.0.0.1
      - MONGO_PORT=
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=root
      - MONGO_DATABASE=wechat
      - MONGO_COLLECTION=wechat
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=weixin
    depends_on:
      - redis
      - mongo
      - mysql

  redis:
    image: redis/redis-stack:7.4.0-v3
    container_name: weixin-redis
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
  
  mongo:
    image: mongo:8.0.8
    container_name: weixin-mongodb
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 3
  
  mysql:
    image: mysql:5.7.44
    container_name: weixin-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    network_mode: bridge
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mysql_data/data/:/var/lib/mysql
      - ./mysql_data/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql_data/log:/var/log/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./initdb/:/docker-entrypoint-initdb.d/
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p", "root"]
      interval: 5s
      timeout: 3s
      retries: 3