services:
  weixin-mp:
    image: henryhe613/weixin-mp:0.1
    container_name: weixin-mp
    network_mode: host
    restart: unless-stopped
    environment:
      - APPID=
      - APPSECRET=
      - OPENID=
      - TEMPLATE_ID=
      - VERIFY_TOKEN=
      - WEB_PORT=80
      - REDIS_HOST=weixin-redis
      - REDIS_PORT=6379
      - REDIS_DB=0

  weixin-redis:
    image: redis/redis-stack:latest
    container_name: weixin-redis
    restart: unless-stopped
    networks_mode: bridge
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis_data:/data
  
  mongo:
    image: mongo:latest
    container_name: weixin-mongodb
    restart: unless-stopped
    networks_mode: bridge
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo_data:/data/db
  
  mysql:
    image: mysql:5.7.44
    container_name: weixin-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    network_mode: bridge
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mysql_data/data/:/var/lib/mysql
      - ./mysql_data/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql_data/log:/var/log/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1